---
title: "1.1 - Definitions of Statistics, Probability, and Key Terms"
---

{{< include preamble.qmd >}}

-   The science of **statistics** deals with the collection, interpretation, and presentation of **data**.

-   In this course, you will learn how to:

1.  organize and summarize data (**descriptive statistics**).
    -   Think creating a graph, or using an average
2.  Use formal methods for drawing conclusions from *good* data (**inferential statistics**).
    -   Uses probability to determine how confident we are in our conclusions

-   Effective interpretation is based on good procedures for producing data and thoughtful examination of the data.

-   While it may feel there are many formulas, the goal is not to perform numerous calculations, but to gain an understanding of your data.

-   Calculations can be done by a computer, understanding comes from **you**.

## Statistical Models

-   Similar to all other branches of math, statistics uses **mathematical models** to describe phenomena in the real world. Some mathematical models are deterministic: a value is precisely determined by another value.
    -   Acceleration of a car from rest
    -   Heat transfer from a stove to a pot
    -   $\blanker{5cm}$
    -   $\blanker{5cm}$
-   However, life is not always precise. **Statistical models** can be used to predict life's more uncertain situations. They can describe the probability or likelihood of an event occurring and provide alternative outcomes.
    -   Weather forecasts
    -   $\blanker{5cm}$
    -   $\blanker{5cm}$

## Probability

-   **Probability** is a mathematical tool to study randomness and deals with the chance of an event occurring.\
-   If you toss a fair coin 4 times, the outcome may not be two heads and two tails
-   However if you toss the same coin 4,000 times, the outcomes will be close to 50/50.
-   A few repetitions are uncertain, but there is a pattern of outcomes with many repetitions.

## Key terms

-   **population**: a collection of people, objects, etc, under study
-   **sample**: a portion or subset of the population
-   **statistic**: a number that represents a property of the sample
-   **parameter**: a number that represents a property of the population
-   **representative sample**: a sample that contains characteristics of the population
-   **variable**: characteristic or measurement that can be determined for each member of a population
    -   numerical variable: values with equal units (weight in pounds, time in hours)
    -   categorical variable: places person/thing into a category (party affiliation, hair color)
-   **data**: single value of the variable

::: {.callout-note icon="false"}
## Example 1

Determine what the population, sample, parameter, statistic, variable, and data referred to in the following study.  
We want to know the mean amount of extracurricular activities in which high school students participate. We randomly surveyed 100 high school students. Three of those students were in 2, 5, and 7 extracurricular activities, respectively.

**Solution**  

- **population**: all high school students  
- **sample** : 100 high school students interviewed  
- **parameter**: mean amount of extracurricular activities in which all high school students participate  
- **statistic**: mean amount of extracurricular activities in which the sample of high school students participate  
- **variable**: let $X=$ the amount of extracurricular activities by one high school student  
- **data**: the number of extracurricular activities in which the high school students participate. Includes 2, 5, and 7.  

:::

::: {.callout-note icon="false"}
## Example 2

A study was conducted at a local high school to analyze the average cumulative GPAs of students who graduated last year. Fill in the letter of the phrase that best describes each of the items below

1. Population $\blank$ 2. Statistic $\blank$ 3. Parameter $\blank$ 4. Sample $\blank$ 5. Variable $\blank$ 6. Data $\blank$

a. all students who attended the high school last year
b. the cumulative GPA of one student who graduated last year
c. 3.65, 2.80, 1.50, 3.90
d. a group of students who graduated from the high school last year, randomly selected
e. the average cumulative GPA of students who graduated from the high school last year
f. all students who graduated from the high school last year
g. the average cumulative GPA of students in the study who graduated from high school last year. 
:::

::: {.callout-note icon="false"}
## Example 3

An insurance company would like to determine the proportion of all medical doctors who have been involved in one or more malpractice lawsuits. The company selects 500 doctors at random from a professional directory and determines the number in the sample who have been involved in a malpractice lawsuit


* **population**: 
* **sample** : 
* **parameter**: 
* **statistic**: 
* **variable**: 
* **data**:  
:::

\newpage

## Homework 

For the four following exercises, identify: a. the population, b. the sample, c. the parameter, d. the statistic, e. the variable, and f. the data. Give examples where appropriate 

1. A fitness center is interested in the mean amount of time a client exercises in the center each week. 

`r spacer()`

2. Ski resorts are interested in the mean age that children take their first ski and snowboarding lessons. They need this information to plan their ski classes optimally. 

`r spacer()`

3. A cardiologist is interested in the mean recovery period of her patients who have had heart attacks.

`r spacer()`

4. Insurance companies are interested in the mean health costs each year of their clients, so that they can determine the cost of health insurance. 

`r spacer()`

For the three following exercises: A Lake Tahoe Community College (LTCC) instructor is interested in the mean number of days Lake Tahoe Community College math students are absent from class during a quarter. 

5. What is the population that she is interested in? 
    a. all LTCC students
    b. all LTCC English students
    c. all LTCC students in her classes
    d. all LTCC math students

6. Consider the following: $X=$ the number of days a LTCC math student is absent. 
In this case, $X$ is an example of which of the following?  
    a. variable
    b. population
    c. statistic
    d. data

7. The instructor's sample produces a mean number of days absent of 3.5 days. This value is an example of which of the following?  
    a. parameter
    b. data
    c. statistic
    d. variable