---
title: "1.3 - Frequency, Frequency Tables, and Levels of Measurement"
---

{{< include preamble.qmd >}}

## Levels of measurement 

:::: {layout="[0.5,-.1, 0.5]" fig-pos="H"}
:::{#firstcol}
**Nominal Scale Level** 

* Categorical data: categories, colors, names, labels, favorite food, yes/no 
* Not ordered - e.g. favorite foods $\blanker{5cm}$

**Ordinal Scale Level** 

* Categorical data
* Can be ordered - e.g. top 5 $\blanker{5cm}$

:::
:::{#secondcol}
**Interval Scale Level** 

* Numeric data, differences are meaningful, but ratios are not 
* Does not have a definite 0
* e.g. Temperature $^\circ C$: $80^\circ \text C - 40^\circ \text C = 40 ^\circ \text C$ makes sense but $80^\circ \text C$ is not twice as hot as $40^\circ \text C$

**Ratio Scale Level** 

* Numeric data, more calculation possible and ratios make sense
* Has a definite 0
* e.g. mass, race time, test scores

:::
::::

::: {.callout-note icon="false"}
### Example 1 
What type of measure scale is being used (nominal, ordinal, interval, ratio)? 

a. High school soccer players classified by their athletic ability: superior, above average, average, below average $\blanker{4cm}$

b. Baking temperatures for various dishes: $350 ^\circ \text F, 400^\circ \text F, 325 ^\circ \text F, 250 ^\circ \text F$ $\blanker{4cm}$ 

c. The colors of crayons in a 24-crayon box $\blanker{4cm}$ 

d. Social security numbers $\blanker{4cm}$ 

e. Incomes measured in dollars $\blanker{4cm}$ 

f. A satisfaction survey of a social website by number: 1 = very satisfied, 2 = somewhat satisfied, 3 = not satisfied $\blanker{4cm}$ 

g. Preferred TV shows: comedy, drama, science fiction, sports, news $\blanker{4cm}$ 

h. Time of day on an analog watch $\blanker{4cm}$ 

i. The distance in miles to the closest grocery store $\blanker{4cm}$ 

j. The dates 1066, 1492, 1644, 1944, and 1947 $\blanker{4cm}$ 

k. The heights of 21-65 year-old women $\blanker{4cm}$ 

l. Letter grades: A, B, C, D, and F $\blanker{4cm}$ 

:::

## Frequency 

Twenty students were asked how many hours they worked per day. Their responses, in hours, were as follows: 5, 6, 3, 3, 2, 4, 7, 5, 2, 3, 5, 6, 5, 4, 4, 3, 5, 2, 5, 3. @tbl-tbl1 lists the different data values. 

::: {#tbl-tbl1 tbl-pos="h"}
```{=latex}
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{c | c | c | c}
\textbf{Data Value (hours)} & \textbf{Frequency} & \textbf{Relative Frequency} & \makecell{\textbf{Cumulative Relative} \\ \textbf{Frequency}} \\
\hline
2 & 3 & $\frac{3}{20} \text{ or } .15$ & .15 \\
3 & 5 & $\frac{5}{20} \text { or } .25$ & .15 + .25 = .40 \\
4 & 3 & $\frac{3}{20} \text { or } .15$ & .40 + .15 = .55 \\
5 & 6 & $\frac{6}{20} \text { or } .30$ & .55 + .30 = .85 \\
6 & 2 & $\frac{2}{20} \text { or } .10$ & .85 + .10 = .95 \\
7 & 1 & $\frac{1}{20} \text { or } .05$ & .95 + .05 = 1.00 \\
\end{tabular}
```

Frequency table of student work hours with relative and cumulative relative frequencies
:::

* **Frequency**: number of times a value of the data occurs 
* **Relative Frequency**: ratio of *frequency* to total outcomes 
* **Cumulative Relative Frequency**: accumulation of previous relative frequencies 

::: {.callout-note icon="false"}
### Example 2 

::: {#tbl-tbl2 tbl-pos="h"}
```{=latex}
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{c | c | c | c}
\textbf{Height (inches)} & \textbf{Frequency} & \textbf{Relative Frequency} & \makecell{\textbf{Cumulative Relative} \\ \textbf{Frequency}} \\
\hline
59.95-61.95 & 5 & $\frac{5}{100} = .05$ & .05 \\
61.95-63.95 & 3 & $\frac{3}{100} = .03$ & .03 + .05 = 08 \\
63.95-65.95 & 15 & $\frac{15}{100} = .15$ & .08 + .15 = .23 \\
65.95-67.95 & 40 & $\frac{40}{100} = .40$ & .23 + .40 = .63 \\
67.95-69.95 & 17 & $\frac{17}{100} = .17$ & .63 + .17 = .80 \\
69.95-71.95 & 12 & $\frac{12}{100} = .12$ & .80 + .12 = .92 \\
71.95-73.95 & 7 & $\frac{7}{100} = .07$ & .92 + .07 = .99 \\
73.95-75.95 & 1 & $\frac{1}{100} = .01$ & .99 + .01 = 1.00 \\
\end{tabular}
```

Frequency table of soccer player height
:::

Use @tbl-tbl2 to answer the following questions: 

1. Find the percentage of heights that are less than 65.95 inches. 

`r spacer(1)`

2. Find the percentage of heights that fall between 61.95 and 65.95 inches.

`r spacer(1)` 

3. Find the percentage of heights that are from 67.95-71.95 inches. 

`r spacer(1)`

4. Find the percentage of heights that are from 67.95-73.5 inches. 

`r spacer(1)` 

5. Find the percentage of heights that are more than 65.95 inches. 

`r spacer(1)`

6. Find the number of players in the sample who are between 61.95 and 71.95 inches tall. 

`r spacer(1)` 

7. What kind of data are the heights? 

`r spacer(1)` 

8. Describe how you could gather the data (heights) so that the data are representative of all male semiprofessional soccer players. 

`r spacer(1)`
:::

## Homework 

1. Sixty adults with gum disease were asked the number of times per week they used to floss before their diagnosis. The (incomplete) results are showin in @tbl-tbl3 

::: {#tbl-tbl3 tbl-pos="h"}
```{=latex}
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{c | c | c | c}
\textbf{\# Flossing per week} & \textbf{Frequency} & \textbf{Relative Frequency} & \makecell{\textbf{Cumulative Relative} \\ \textbf{Frequency}} \\
\hline
0 & 27 & .4500 &  \\
1 & 18 &  & \\
3 &  &  & .9333 \\
6 & 3 & .0500 & \\
7 & 1 & .0167 & \\
\end{tabular}
```

Flossing frequency for adults with gum disease
:::

a. Fill in the blanks in @tbl-tbl3 
b. What percent of adults flossed six times per week? 
c. What percent flossed at most three times per week? 

2. A business magazine published data on the best small firms in 2012. These were firms which had been publicly traded for at least a year, have a stock price of at least \$5 per share, and have reported annual revenue between \$5 million and \$1 billion. @tbl-tbl4 shows the ages of the chief executive officers for the first 60 ranked firms. 

::: {#tbl-tbl4 tbl-pos="h"}
```{=latex}
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{c | c | c | c}
\textbf{Age} & \textbf{Frequency} & \textbf{Relative Frequency} & \makecell{\textbf{Cumulative Relative} \\ \textbf{Frequency}} \\
\hline
40-44 & 3 &  &  \\
45-49 & 11 &  &  \\
50-54 & 13 &  &  \\
55-59 & 16 &  &  \\
60-64 & 10 &  &  \\
65-69 & 6 &  &  \\
70-74 & 1 &  &  \\
\end{tabular}
```


:::

a. What is the frequency for CEO ages between 54 and 65? 
b. What percentage of CEOs are 65 years or older? 
c. What is the relative frequency of ages under 50? 
d. What is the cumulative relative frequency for CEOs younger than 55? 
