% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={8.2 - A single population mean using the Student's t-Distribution},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{8.2 - A single population mean using the Student's
t-Distribution}
\author{}
\date{}

\begin{document}
\maketitle


\subsection{Student's t-Distribution}\label{students-t-distribution}

\begin{itemize}
\tightlist
\item
  In practice, we rarely know the population standard deviation
  \(\sigma\) so how can we calculate a confidence interval?\\
\item
  Historically, when sample size \(n\) was large, the unknown \(\sigma\)
  did not bother statisticians: they used sample standard deviation
  \(s\) to approximate \(\sigma\).
\item
  However for small \(n\), a confidence interval based on \(s\) is not
  accurate.

  \begin{itemize}
  \tightlist
  \item
    Discovered by William Gosset (1876-1937) while working at Guinness.
  \item
    His small sample of barley and hops did not produce accurate
    confidence intervals when replacing \(\sigma\) with \(s\).
  \item
    He discovered that the normal distribution was not accurate, the
    actual distribution depended on sample size.
  \item
    He published results under pen name \emph{Student} so the
    distribution was dubbed the \textbf{Student's \emph{t}-distribution}
  \end{itemize}
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, bottomrule=.15mm, rightrule=.15mm, leftrule=.75mm, opacityback=0, left=2mm, colframe=quarto-callout-note-color-frame, arc=.35mm, breakable, toprule=.15mm, colback=white]
\begin{minipage}[t]{5.5mm}
\textcolor{quarto-callout-note-color}{\faInfo}
\end{minipage}%
\begin{minipage}[t]{\textwidth - 5.5mm}

\vspace{-3mm}\textbf{Student's \emph{t}-Distribution}\vspace{3mm}

\begin{itemize}
\tightlist
\item
  Used whenever we are using \(s\) as estimate for \(\sigma\).
\item
  If you draw random sample of size \(n\) from population with
  approximately normal distribution with mean \(\mu\) and unknown
  standard deviation \(\sigma\):

  \begin{itemize}
  \tightlist
  \item
    Calculate \emph{t}-score \(t=\frac{\bar x - \mu}{s/\sqrt n}\)
  \item
    The \emph{t}-score will follow a \emph{Student's t-distribution}
    with \(n-1\) degrees of freedom
  \end{itemize}
\item
  The exact shape depends on the degrees of freedom (df); as the df
  increase, the distribution looks more like the normal distribution.
\end{itemize}

\begin{figure}[H]

\centering{

\includegraphics{8.2_files/figure-pdf/fig-plot1-1.pdf}

}

\caption{\label{fig-plot1}}

\end{figure}%

In summary: \emph{If the population standard deviation is not known} the
error bound for a population mean is:

\begin{itemize}
\tightlist
\item
  EBM = \((t_{\alpha/2})\left(\frac{s}{\sqrt n}\right)\)
\item
  \(t_{\alpha/2}\) is the \(t\)-score with area to the right equal to
  \(\alpha/2\)
\item
  Use \(df = n-1\) degrees of freedom
\item
  \(s\) = sample standard deviation
\item
  Confidence interval: \(\bar x - EBM, \bar x + EBM)\)
\end{itemize}

\end{minipage}%
\end{tcolorbox}

\subsubsection{Example 1}\label{example-1}

Suppose you do a study of acupuncture to determine how effective it is
in relieving pain. You measure sensory rates for 15 subjects with the
results given. Use the sample data to construct a 95\% confidence
interval for the mean sensory rate for the population (assumed normal)
from which you took the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sensory\_rate }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{8.6}\NormalTok{, }\FloatTok{9.4}\NormalTok{, }\FloatTok{7.9}\NormalTok{, }\FloatTok{6.8}\NormalTok{, }\FloatTok{8.3}\NormalTok{, }\FloatTok{7.3}\NormalTok{, }\FloatTok{9.2}\NormalTok{, }\FloatTok{9.6}\NormalTok{, }\FloatTok{8.7}\NormalTok{, }\FloatTok{11.4}\NormalTok{, }\FloatTok{10.3}\NormalTok{, }\FloatTok{5.4}\NormalTok{, }\FloatTok{8.1}\NormalTok{, }\FloatTok{5.5}\NormalTok{, }\FloatTok{6.9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\paragraph{Solution step-by-step}\label{solution-step-by-step}

To find the confidence interval you need the sample mean \(\bar x\),
sample standard deviation \(\s\), and sample size \(n\), and
\(t_{\alpha/2}\)

\begin{itemize}
\tightlist
\item
  \$\bar x = \$ \texttt{mean(sensory\_rate)} (mean() in Desmos)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xbar }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(sensory\_rate); xbar}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 8.226667
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \(s=\) \texttt{sd(sensory\_rate)} (stdev() in Desmos)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(sensory\_rate); s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.672238
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \(n=\) \texttt{length(sensory\_rate)} (length() in Desmos)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(sensory\_rate); n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 15
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \(t_{\alpha/2}=\) \texttt{qt(.975,14)} (tdist(df), select compute =
  bounds and region = left in Desmos)

  \begin{itemize}
  \tightlist
  \item
    Note this gives 2.5\% area in the top and 2.5\% area in the bottom
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ta2 }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{14}\NormalTok{); ta2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.144787
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Thus to find the EBM:
\end{itemize}

\[
\begin{aligned}
EBM &= (t_{\alpha/2})\left(\frac{s}{\sqrt n}\right) \\
&= (2.145)(\frac{1.6722}{\sqrt {15}})\\
&= 0.926
\end{aligned}
\]

\begin{itemize}
\tightlist
\item
  And the confidence interval is then:
\end{itemize}

\[
(\bar x - EBM, \bar x + EBM)\\
(8.2267 - 0.926,8.2267 - 0.926)\\
(7.30,9.15)
\]

\begin{itemize}
\tightlist
\item
  So we can say ``we estimate with 95\% confidence that the true
  population mean sensory rate is between 7.30 and 9.15.''
\end{itemize}

\paragraph{Solution with R}\label{solution-with-r}

\begin{itemize}
\item
  We can take a data set and use a built-in function called
  \texttt{t.test} to find the confidence interval (as well as other
  information we haven't covered).
\item
  Use \texttt{t.test(data,\ conf.level\ =\ 0.95)\$conf.int}

  \begin{itemize}
  \tightlist
  \item
    We can exclude the \texttt{\$conf.int} and get more information but
    we care primarily about the confidence interval here.
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(sensory\_rate, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}\SpecialCharTok{$}\NormalTok{conf.int}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 7.300612 9.152721
attr(,"conf.level")
[1] 0.95
\end{verbatim}




\end{document}
