---
title: "Statistics Quiz 1.1-1.3"
format: 
  pdf:
    include-in-header:
      text: |
        \newcommand{\blanker}[1]{\underline{\makebox[#1]{}}}
---

{{< include preamble.qmd >}}

Instructions: Please respond to each question as fully as you are able and show all necessary work to receive full credit. Partial credit will be given, so even if you are unsure on a question, make your best effort! 

## Scenario 1: Fitness Craze 
Answer the following questions given the scenario: 

EllisFit, the renowned gym and fitness center, is interested in the mean amount of time per week each of its members exercises at the gym. So, a survey is conducted by randomly selecting 50 EllisFit members and asking each how many hours per week they exercise at the gym. For each of #1-6 state whether it is the population, the parameter, the sample, the statistic, the variable, or the data. 

1. The set of 50 randomly selected members is: $\blanker{4cm}$ 
2. The mean number of hours per week exercised for the group of all EllisFit members is $\blanker{4cm}$ 
3. The number of hours per week one member exercises is $\blanker{4cm}$ 
4. "Four hours" is $\blanker{4cm}$ 
5. The mean number of hours per week exercised for the 50 randomly selected members is $\blanker{4cm}$ 
6. The set of all members of EllisFit is $\blanker{4cm}$ 
7. The type of data is $\blanker{4cm}$ 
    a. Qualitative 
    b. Quantitative Discrete 
    c. Quantitative Continuous 
8. The sampling method used is $\blanker{4cm}$ 
    a. Cluster sampling 
    b. Stratified sampling 
    c. Simple random sampling 
    d. Convenience sampling 
    e. Systematic sampling 
9. The level of measurement is 
    a. Nominal scale 
    b. Ordinal scale 
    c. Interval scale 
    d. Ratio scale

\noindent\rule{\textwidth}{0.4pt}

## Scenario 2: Banamania

Answer the following questions given this scenario:

A food scientist is interested in the ripeness levels of bananas in a warehouse in Miami. She groups the bananas into 541 crates, then randomly chooses 25 crates, then assesses each banana in each of those 25 crates as either *underripe, almost ripe, perfectly ripe, or overripe*. For each of #10-15 state whether it is the population, the parameter, the sample, the statistic, the variable, or the data. 


10. The ripeness of a single banana is $\blanker{4cm}$ 
11. The ripeness of the bananas in the 25 selected crates is $\blanker{4cm}$ 
12. The set of all bananas in the warehouse is $\blanker{4cm}$ 
13. The bananas in the 25 selected crates are $\blanker{4cm}$ 
14. The ripeness of all bananas in the warehouse is $\blanker{4cm}$ 
15. "Perfectly ripe" is $\blanker{4cm}$ 
16. The type of data is $\blanker{4cm}$ 
    a. Qualitative 
    b. Quantitative Discrete 
    c. Quantitative Continuous 
17. The sampling method used is $\blanker{4cm}$ 
    a. Cluster sampling 
    b. Stratified sampling 
    c. Simple random sampling 
    d. Convenience sampling 
    e. Systematic sampling 
18. The level of measurement is 
    a. Nominal scale 
    b. Ordinal scale 
    c. Interval scale 
    d. Ratio scale 

\noindent\rule{\textwidth}{0.4pt}

## Scenario 3: Paper economics 
Answer the following questions given this scenario:

To investigate how much money Americans spend on paper towels each year, researchers divide a map of the USA into six regions. They then call 0.001% of the population in each region via telephone and ask how much each person spends on paper towels. For each of #19-24 state whether it is the population, the parameter, the sample, the statistic, the variable, or the data. 

19. The amount of money spent on paper towels each year by all Americans is $\blanker{4cm}$ 
20. The amount of money spent on paper towels each year by the group of survey respondents is $\blanker{4cm}$ 
21. The set of all Americans is $\blanker{4cm}$ 
22. The group of people who responded to the phone survey is $\blanker{4cm}$ 
23. \$45 is $\blanker{4cm}$ 
24. The amount of money spent by an individual person on paper towels in one year is $\blanker{4cm}$ 
25. The type of data is: 
    a. Qualitative 
    b. Quantitative Discrete 
    c. Quantitative Continuous 
26. The sampling method used is: 
    a. Cluster sampling 
    b. Stratified sampling 
    c. Simple random sampling 
    d. Convenience sampling 
    e. Systematic sampling 
27. The level of measurement is 
    a. Nominal scale 
    b. Ordinal scale 
    c. Interval scale 
    d. Ratio scale 

\noindent\rule{\textwidth}{0.4pt}

## Scenario 4: Immigration Duration 
Sixteen immigrants to the United States were asked how many years, to the nearest year, they have lived in the United States. The data are as follows: 2, 5, 7, 2, 2, 10, 0, 7, 0, 5, 12, 15, 12, 4, 5, 10.
The frequency table below was created from the data. Based on this table, answer the following questions. 

```{=latex}
\begin{tabular}{c | c}
\textbf{Data} & \textbf{Frequency} \\
\hline
0 & 2 \\
2 & 3 \\
4 & 1 \\
5 & 3 \\
7 & 2 \\
10 & 2 \\
12 & 2 \\
15 & 1 \\
\end{tabular}
```

28. What fraction of respondents have lived in the US for exactly 5 years? 

\vspace{3em} 

29. What fraction of respondents have lived in the US for at least 10 years? 

\vspace{3em}

30. What fraction of respondents have lived in the US for 4 years or less? 

\vspace{3em}

\noindent\rule{\textwidth}{0.4pt}

## Scenario 5: Courses Two-Way Table 
Given the following two-way table showing the distribution of students by grade level and the math class they are enrolled in (data pulled from Mr. Young's courses). 
```{=latex}
\begin{tabular}{l | c | c | c | c}
 & \textbf{Algebra II} & \textbf{AP Calculus AB} & \textbf{Statistics} & \textbf{Total}\\
\hline
10th & 10 & 0 & 0 & 10 \\
11th & 8 & 8 & 0 & 16 \\
12th & 0 & 3 & 13 & 16 \\
\hline
Total & 18 & 11 & 13 & 42 \\
\end{tabular}
```

31. What proportion of students are in 10th grade? 

\vspace{3em}

32. What are the proportions of each grade in AP Calculus AB? 

\vspace{3em}

33. What are the proportions of classes taken within the 12th grade? 

\vspace{3em}
\noindent\rule{\textwidth}{0.4pt}

## Scenario 6: Open Ended 

34. Give an example of a quantity measured on the interval scale level, and explain how your example fits the definition of interval scale level. 

